name: Infrastructure
on:
  push:
    branches:
      - main
    paths:
      - 'infrastructure/**'
      - '.github/workflows/infrastructure.main.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'infrastructure/**'
      - '.github/workflows/infrastructure.main.yml'

# Sets permissions of the GITHUB_TOKEN to allow deployment
permissions:
  contents: read
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      LOCATION: eastus
    steps:
      - uses: actions/checkout@v2
      - name: Build Bicep File
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az bicep build --file infrastructure/main.bicep
      - uses: Azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Create Resource Group
        uses: azure/CLI@v1
        with:
          inlineScript: |
              az group create --location ${{ env.LOCATION }} --name ${{ secrets.RESOURCE_GROUP_NAME }}
      - name: Deploy Bicep File
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az deployment group create --resource-group '${{ secrets.RESOURCE_GROUP_NAME }}' --template-file infrastructure/main.bicep \
              --parameters appserviceplanname='${{ secrets.APPSERVICEPLANNAME }}' appname='${{ secrets.APPNAME }}' cosmosdbname='${{ secrets.COSMOSDBNAME }}' \
              --parameters cosmosdatabasename='${{ secrets.COSMOSDATABASENAME }}' storageaccountname='${{ secrets.STORAGEACCOUNTNAME }}'
